#ifndef ADD_GLSL_KEYWORD
	#define ADD_GLSL_KEYWORD(tokName,tokMinVersion, tokMaxVersion, tokDeprecatedVersion, tokClass, tokSubType, tokExtraPtr)  GLSL_KEYWORD_ID_##tokName,
	#define ADD_GLSL_KW_DELIMITER(CustomName) GLSL_KW_DELIMITER_##CustomName,

	#define WAS_ENUMERATION

	enum VHDLKeywordCategory{
		VHDKey_None,
		VHDKey_NeedsEnd
	};


	enum GLSLKeywordID
	{
		GLSL_KEYWORD_ID_NONE,

#endif

ADD_GLSL_KEYWORD(void,			0,0,0,		DATATYPE,	GLSL_VOID,		0)

ADD_GLSL_KW_DELIMITER(SIZED_DATATYPES_BEGIN)
ADD_GLSL_KEYWORD(float,			0,0,0,		VHDKey_None,	GLSL_FLOAT,	0)
ADD_GLSL_KEYWORD(int,			0,0,0,		VHDKey_NeedsEnd,	GLSL_INT,	0)
ADD_GLSL_KEYWORD(uint,			0,0,0,		DATATYPE,	GLSL_UINT,	0)
ADD_GLSL_KEYWORD(bool,			0,0,0,		DATATYPE,	GLSL_BOOL,	0)
ADD_GLSL_KEYWORD(double,		0,0,0,		DATATYPE,	GLSL_DOUBLE,0)

ADD_GLSL_KEYWORD(vec2,			0,0,0,		DATATYPE,	GLSL_VEC2,		0)
ADD_GLSL_KEYWORD(vec3,			0,0,0,		DATATYPE,	GLSL_VEC3,		0)
ADD_GLSL_KEYWORD(vec4,			0,0,0,		DATATYPE,	GLSL_VEC4,		0)
ADD_GLSL_KEYWORD(ivec2,			0,0,0,		DATATYPE,	GLSL_IVEC2,		0)
ADD_GLSL_KEYWORD(ivec3,			0,0,0,		DATATYPE,	GLSL_IVEC3,		0)
ADD_GLSL_KEYWORD(ivec4,			0,0,0,		DATATYPE,	GLSL_IVEC4,		0)
ADD_GLSL_KEYWORD(uvec2,			0,0,0,		DATATYPE,	GLSL_UVEC2,		0)
ADD_GLSL_KEYWORD(uvec3,			0,0,0,		DATATYPE,	GLSL_UVEC3,		0)
ADD_GLSL_KEYWORD(uvec4,			0,0,0,		DATATYPE,	GLSL_UVEC4,		0)
ADD_GLSL_KEYWORD(bvec2,			0,0,0,		DATATYPE,	GLSL_BVEC2,		0)
ADD_GLSL_KEYWORD(bvec3,			0,0,0,		DATATYPE,	GLSL_BVEC3,		0)
ADD_GLSL_KEYWORD(bvec4,			0,0,0,		DATATYPE,	GLSL_BVEC4,		0)
ADD_GLSL_KEYWORD(dvec2,			0,0,0,		DATATYPE,	GLSL_DVEC2,		0)
ADD_GLSL_KEYWORD(dvec3,			0,0,0,		DATATYPE,	GLSL_DVEC3,		0)
ADD_GLSL_KEYWORD(dvec4,			0,0,0,		DATATYPE,	GLSL_DVEC4,		0)

ADD_GLSL_KEYWORD(mat2,			0,0,0,		DATATYPE,	GLSL_MAT2,		0)
ADD_GLSL_KEYWORD(mat3,			0,0,0,		DATATYPE,	GLSL_MAT3,		0)
ADD_GLSL_KEYWORD(mat4,			0,0,0,		DATATYPE,	GLSL_MAT4,		0)

ADD_GLSL_KEYWORD(mat2x2,		0,0,0,		DATATYPE,	GLSL_MAT2,		0)
ADD_GLSL_KEYWORD(mat3x3,		0,0,0,		DATATYPE,	GLSL_MAT3,		0)
ADD_GLSL_KEYWORD(mat4x4,		0,0,0,		DATATYPE,	GLSL_MAT4,		0)

ADD_GLSL_KEYWORD(mat2x3,		0,0,0,		DATATYPE,	GLSL_MAT2x3,	0)
ADD_GLSL_KEYWORD(mat2x4,		0,0,0,		DATATYPE,	GLSL_MAT2x4,	0)
ADD_GLSL_KEYWORD(mat3x2,		0,0,0,		DATATYPE,	GLSL_MAT3x2,	0)
ADD_GLSL_KEYWORD(mat3x4,		0,0,0,		DATATYPE,	GLSL_MAT3x4,	0)
ADD_GLSL_KEYWORD(mat4x2,		0,0,0,		DATATYPE,	GLSL_MAT4x2,	0)
ADD_GLSL_KEYWORD(mat4x3,		0,0,0,		DATATYPE,	GLSL_MAT4x3,	0)

ADD_GLSL_KEYWORD(dmat2,			0,0,0,		DATATYPE,	GLSL_DMAT2,		0)
ADD_GLSL_KEYWORD(dmat3,			0,0,0,		DATATYPE,	GLSL_DMAT3,		0)
ADD_GLSL_KEYWORD(dmat4,			0,0,0,		DATATYPE,	GLSL_DMAT4,		0)

ADD_GLSL_KEYWORD(dmat2x2,		0,0,0,		DATATYPE,	GLSL_DMAT2,		0)
ADD_GLSL_KEYWORD(dmat3x3,		0,0,0,		DATATYPE,	GLSL_DMAT3,		0)
ADD_GLSL_KEYWORD(dmat4x4,		0,0,0,		DATATYPE,	GLSL_DMAT4,		0)

ADD_GLSL_KEYWORD(dmat2x3,		0,0,0,		DATATYPE,	GLSL_DMAT2x3,	0)
ADD_GLSL_KEYWORD(dmat2x4,		0,0,0,		DATATYPE,	GLSL_DMAT2x4,	0)
ADD_GLSL_KEYWORD(dmat3x2,		0,0,0,		DATATYPE,	GLSL_DMAT3x2,	0)
ADD_GLSL_KEYWORD(dmat3x4,		0,0,0,		DATATYPE,	GLSL_DMAT3x4,	0)
ADD_GLSL_KEYWORD(dmat4x2,		0,0,0,		DATATYPE,	GLSL_DMAT4x2,	0)
ADD_GLSL_KEYWORD(dmat4x3,		0,0,0,		DATATYPE,	GLSL_DMAT4x3,	0)
ADD_GLSL_KW_DELIMITER(SIZED_DATATYPES_END)


ADD_GLSL_KEYWORD(sampler2D,		0,0,0,		DATATYPE,	GLSL_SAMPLER2D,	0)




ADD_GLSL_KEYWORD(uniform,		0,0,0,		LANG,		0,						0)
ADD_GLSL_KEYWORD(in,			0,0,0,		LANG,		0,						0)
ADD_GLSL_KEYWORD(out,			0,0,0,		LANG,		0,						0)

ADD_GLSL_KEYWORD(if,			0,0,0,		LANG,		0,						0)
ADD_GLSL_KEYWORD(return,		0,0,0,		LANG,		0,						0)
ADD_GLSL_KEYWORD(for,			0,0,0,		LANG,		0,						0)


/*
ADD_GLSL_KEYWORD(x,				0,0,0,		SWIZZLE,	MAKE_SWIZ(1,1,SWIZ_X,0,0,0),			0)
ADD_GLSL_KEYWORD(y,				0,0,0,		SWIZZLE,	MAKE_SWIZ(1,2,SWIZ_Y,0,0,0),			0)
ADD_GLSL_KEYWORD(z,				0,0,0,		SWIZZLE,	MAKE_SWIZ(1,3,SWIZ_Z,0,0,0),			0)
ADD_GLSL_KEYWORD(w,				0,0,0,		SWIZZLE,	MAKE_SWIZ(1,4,SWIZ_W,0,0,0),			0)

ADD_GLSL_KEYWORD(xx,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,1,SWIZ_X,SWIZ_X,0,0),			0)
ADD_GLSL_KEYWORD(xy,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,2,SWIZ_X,SWIZ_Y,0,0),			0)
ADD_GLSL_KEYWORD(xz,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,3,SWIZ_X,SWIZ_Z,0,0),			0)
ADD_GLSL_KEYWORD(xw,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,4,SWIZ_X,SWIZ_W,0,0),			0)

ADD_GLSL_KEYWORD(yx,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,2,SWIZ_Y,SWIZ_X,0,0),			0)
ADD_GLSL_KEYWORD(yy,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,2,SWIZ_Y,SWIZ_Y,0,0),			0)
ADD_GLSL_KEYWORD(yz,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,3,SWIZ_Y,SWIZ_Z,0,0),			0)
ADD_GLSL_KEYWORD(yw,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,4,SWIZ_Y,SWIZ_W,0,0),			0)

ADD_GLSL_KEYWORD(zx,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,3,SWIZ_Z,SWIZ_X,0,0),			0)
ADD_GLSL_KEYWORD(zy,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,3,SWIZ_Z,SWIZ_Y,0,0),			0)
ADD_GLSL_KEYWORD(zz,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,3,SWIZ_Z,SWIZ_Z,0,0),			0)
ADD_GLSL_KEYWORD(zw,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,4,SWIZ_Z,SWIZ_W,0,0),			0)

ADD_GLSL_KEYWORD(wx,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,4,SWIZ_W,SWIZ_X,0,0),			0)
ADD_GLSL_KEYWORD(wy,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,4,SWIZ_W,SWIZ_Y,0,0),			0)
ADD_GLSL_KEYWORD(wz,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,4,SWIZ_W,SWIZ_Z,0,0),			0)
ADD_GLSL_KEYWORD(ww,			0,0,0,		SWIZZLE,	MAKE_SWIZ(2,4,SWIZ_W,SWIZ_W,0,0),			0)


ADD_GLSL_KEYWORD(xxx,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,1,SWIZ_X,SWIZ_X,SWIZ_X,0),		0)
ADD_GLSL_KEYWORD(xxy,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,2,SWIZ_X,SWIZ_X,SWIZ_Y,0),		0)
ADD_GLSL_KEYWORD(xxz,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,3,SWIZ_X,SWIZ_X,SWIZ_Z,0),		0)
ADD_GLSL_KEYWORD(xxw,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,4,SWIZ_X,SWIZ_X,SWIZ_W,0),		0)


ADD_GLSL_KEYWORD(xyx,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,2,SWIZ_X,SWIZ_Y,SWIZ_X,0),		0)
ADD_GLSL_KEYWORD(xyy,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,2,SWIZ_X,SWIZ_Y,SWIZ_Y,0),		0)
ADD_GLSL_KEYWORD(xyz,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,3,SWIZ_X,SWIZ_Y,SWIZ_Z,0),		0)
ADD_GLSL_KEYWORD(xyw,			0,0,0,		SWIZZLE,	MAKE_SWIZ(3,4,SWIZ_X,SWIZ_Y,SWIZ_W,0),		0)

*/


#ifdef WAS_ENUMERATION
		GLSL_NUM_KEYWORDS
	};
#endif

#undef WAS_ENUMERATION
#undef ADD_GLSL_KEYWORD
#undef ADD_GLSL_KW_DELIMITER
